---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom:
    - find:
        path: "PROBABILITY_"
      rewrite:
        - regexp:
            source: "PROBABILITY_(.+)"
            target: "$1"
