---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 0
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ .Release.Name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 500
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - mountPath: /data
              name: {{ .Release.Name }}
          env:
            - name: DATA_PATH
              value: /data/probability
            - name: MPLCONFIGDIR
              value: /data/matplotlib
            - name: TRY_GOLDEN_FIVE
              value: "{{ .Values.telegram.tryGoldenFive }}"
            - name: SLEEP_TIME
              value: "{{ .Values.telegram.sleepTime }}"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
